In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.colors import ListedColormap
from sklearn import neighbors, datasets
from sklearn.multioutput import MultiOutputClassifier

In [6]:
dataset = pd.read_csv("../data/prepared_data/dataset.csv")
dataset.head()

,machineID,datetime,error1,error2,error3,error4,error5,total_error,error1_24,error2_24,...,vibration_mean,vibration_std,model,age,comp1,comp2,comp3,comp4,total_failure,failure_bool
0,1,2015-01-01 09:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,39.571655,4.808836,model3,18,0.0,0.0,0.0,0.0,0.0,False
1,1,2015-01-01 12:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,34.799816,8.414362,model3,18,0.0,0.0,0.0,0.0,0.0,False
2,1,2015-01-01 15:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,40.288677,5.011355,model3,18,0.0,0.0,0.0,0.0,0.0,False
3,1,2015-01-01 18:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,41.776012,2.889493,model3,18,0.0,0.0,0.0,0.0,0.0,False
4,1,2015-01-01 21:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,44.042853,6.098198,model3,18,0.0,0.0,0.0,0.0,0.0,False